[tool.poetry]
name = "simple-pymq"
version = "0.1.0"
description = "Simple python message queue framework is ready to serve."
authors = ["Allen Chou <f1470891079@gmail.com>"]
readme = "README.md"
packages = [{include = "simple_pymq"}]

[tool.poetry.dependencies]
python = ">=3.8.0,<3.11.0"


[tool.poetry.group.dev.dependencies]
yapf = "*"
flake8 = "*"
flake9 = "*"
black = "*"
pytest = "*"
pytest-asyncio = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
